name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'gaitsetpy/**'
      - 'generate_docs.py'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'gaitsetpy/**'
      - 'generate_docs.py'
      - 'requirements.txt'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate documentation
      run: |
        python generate_docs.py
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit documentation changes
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "No documentation changes to commit"
        else
          git commit -m "Auto-update documentation [skip ci]"
          git push origin HEAD:${GITHUB_REF_NAME}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 